spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/diarypersonal
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect